package university.model;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.*;

/**
 * Simple academic performance report generated by a Manager.
 */
public class Report implements Serializable {
    private static final long serialVersionUID = 1L;

    private final LocalDate    generatedDate;
    private final List<Student> students;

    public Report(List<Student> students) {
        this.students      = List.copyOf(students);
        this.generatedDate = LocalDate.now();
    }

    public double getAverageGpa() {
        return students.stream()
                       .mapToDouble(Student::getGpa)
                       .average()
                       .orElse(0.0);
    }

    public long countPassed() {
        return students.stream()
                       .flatMap(s -> s.getMarks().stream())
                       .filter(Mark::isPassed)
                       .count();
    }

    public long countFailed() {
        return students.stream()
                       .flatMap(s -> s.getMarks().stream())
                       .filter(m -> !m.isPassed())
                       .count();
    }

    public Student getTopStudent() {
        return students.stream()
                       .max(Comparator.comparingDouble(Student::getGpa))
                       .orElse(null);
    }

    @Override
    public String toString() {
        return String.format(
            "=== ACADEMIC REPORT [%s] ===\n" +
            "Students      : %d\n" +
            "Average GPA   : %.2f\n" +
            "Passed marks  : %d\n" +
            "Failed marks  : %d\n" +
            "Top student   : %s\n" +
            "========================",
            generatedDate, students.size(),
            getAverageGpa(), countPassed(), countFailed(),
            getTopStudent() != null ? getTopStudent().getLogin() : "N/A"
        );
    }
}
